version: '3.5'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME_PRODUCTION}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  production-app:
    build:
      context: .
      target: production
    ports:
      - 8080:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=production